# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Admin.create(email: "admin@alphadeal.co", password: "groupsitE619", password_confirmation: "groupsitE619")

Type.create(name: "Phone call")
Type.create(name: "Dinner")
Type.create(name: "Meeting")
Type.create(name: "Task")
Type.create(name: "Target")
Type.create(name: "Email")

Visibility.create(name: "Everyone in my team")
Visibility.create(name: "Creator Only")

Plan.create(name: "Grande", number_users: 10, duration: 12, price: 84)

Currency.create(country: "Algeria", extension: "د.ج")
Currency.create(country: "Andorra", extension: "€")
Currency.create(country: "Angola", extension: "Kz")
Currency.create(country: "Argentina", extension: "$")
Currency.create(country: "Aruba", extension: "ƒ")
Currency.create(country: "Ascension Island", extension: "£")
Currency.create(country: "Australia", extension: "$")
Currency.create(country: "Austria", extension: "€")
Currency.create(country: "Bahamas, The", extension: "$")
Currency.create(country: "Bahrain", extension: ".د.ب")
Currency.create(country: "Bangladesh", extension: "৳")
Currency.create(country: "Barbados", extension: "$")
Currency.create(country: "Belarus", extension: "Br")
Currency.create(country: "Belgium", extension: "€")
Currency.create(country: "Belize", extension: "$")
Currency.create(country: "Benin", extension: "Fr")
Currency.create(country: "Bermuda", extension: "$")
Currency.create(country: "Bolivia", extension: "Bs.")
Currency.create(country: "Bonaire", extension: "$")
Currency.create(country: "Botswana", extension: "P")
Currency.create(country: "Brazil", extension: "R$")
Currency.create(country: "Brunei", extension: "$")
Currency.create(country: "Bulgaria", extension: "лв")
Currency.create(country: "Burkina Faso", extension: "Fr")
Currency.create(country: "Burundi", extension: "Fr")
Currency.create(country: "Cameroon", extension: "Fr")
Currency.create(country: "Canada", extension: "$")
Currency.create(country: "Cape Verde", extension: "Esc")
Currency.create(country: "Cayman Islands", extension: "$")
Currency.create(country: "Central African Republic", extension: "Fr")
Currency.create(country: "Chad", extension: "Fr")
Currency.create(country: "Chile", extension: "$")
Currency.create(country: "China", extension: "¥")
Currency.create(country: "Cocos (Keeling) Islands", extension: "$")
Currency.create(country: "Colombia", extension: "$")
Currency.create(country: "Comoros", extension: "Fr")
Currency.create(country: "Congo, Democratic Republic of the", extension: "Fr")
Currency.create(country: "Congo, Republic of the", extension: "Fr")
Currency.create(country: "Cook Islands", extension: "$")
Currency.create(country: "Costa Rica", extension: "₡")
Currency.create(country: "Côte d'Ivoire", extension: "Fr")
Currency.create(country: "Croatia", extension: "kn")
Currency.create(country: "Cuba", extension: "$")
Currency.create(country: "Curaçao", extension: "ƒ")
Currency.create(country: "Cyprus", extension: "€")
Currency.create(country: "Czech Republic", extension: "Kč")
Currency.create(country: "Denmark", extension: "kr")
Currency.create(country: "Djibouti", extension: "Fr")
Currency.create(country: "Dominica", extension: "$")
Currency.create(country: "Dominican Republic", extension: "$")
Currency.create(country: "East Timor", extension: "$")
Currency.create(country: "Ecuador", extension: "$")
Currency.create(country: "Egypt", extension: "£")
Currency.create(country: "El Salvador", extension: "$")
Currency.create(country: "Equatorial Guinea", extension: "Fr")
Currency.create(country: "Eritrea", extension: "Nfk")
Currency.create(country: "Estonia", extension: "€")
Currency.create(country: "Ethiopia", extension: "Br")
Currency.create(country: "Falkland Islands", extension: "£")
Currency.create(country: "Faroe Islands", extension: "kr")
Currency.create(country: "Fiji", extension: "$")
Currency.create(country: "Finland", extension: "€")
Currency.create(country: "France", extension: "€")
Currency.create(country: "French Polynesia", extension: "Fr")
Currency.create(country: "Gabon", extension: "Fr")
Currency.create(country: "Germany", extension: "€")
Currency.create(country: "Ghana", extension: "₵")
Currency.create(country: "Gibraltar", extension: "£")
Currency.create(country: "Greece", extension: "€")
Currency.create(country: "Grenada", extension: "$")
Currency.create(country: "Guatemala", extension: "Q")
Currency.create(country: "Guernsey", extension: "£")
Currency.create(country: "Guinea", extension: "Fr")
Currency.create(country: "Guinea-Bissau", extension: "Fr")
Currency.create(country: "Guyana", extension: "$")
Currency.create(country: "Haiti", extension: "G")
Currency.create(country: "Honduras", extension: "L")
Currency.create(country: "Hong Kong", extension: "$")
Currency.create(country: "Hungary", extension: "Ft")
Currency.create(country: "Iceland", extension: "kr")
Currency.create(country: "India", extension: "₹")
Currency.create(country: "Indonesia", extension: "Rp")
Currency.create(country: "Iraq", extension: "ع.د")
Currency.create(country: "Ireland", extension: "€")
Currency.create(country: "Isle of Man", extension: "£")
Currency.create(country: "Israel", extension: "₪")
Currency.create(country: "Italy", extension: "€")
Currency.create(country: "Jamaica", extension: "$")
Currency.create(country: "Japan", extension: "¥")
Currency.create(country: "Jersey", extension: "£")
Currency.create(country: "Jordan", extension: "د.ا")
Currency.create(country: "Kazakhstan", extension: "₸")
Currency.create(country: "Kenya", extension: "Sh")
Currency.create(country: "Kiribati", extension: "$")
Currency.create(country: "Korea, North", extension: "₩")
Currency.create(country: "Korea, South", extension: "₩")
Currency.create(country: "Kosovo", extension: "€")
Currency.create(country: "Kuwait", extension: "د.ك")
Currency.create(country: "Kyrgyzstan", extension: "с")
Currency.create(country: "Laos", extension: "₭")
Currency.create(country: "Latvia", extension: "€")
Currency.create(country: "Lebanon", extension: "ل.ل")
Currency.create(country: "Lesotho", extension: "L")
Currency.create(country: "Liberia", extension: "$")
Currency.create(country: "Libya", extension: "ل.د")
Currency.create(country: "Liechtenstein", extension: "Fr")
Currency.create(country: "Lithuania", extension: "€")
Currency.create(country: "Luxembourg", extension: "€")
Currency.create(country: "Macau", extension: "P")
Currency.create(country: "Macedonia, Republic of", extension: "ден")
Currency.create(country: "Madagascar", extension: "Ar")
Currency.create(country: "Malawi", extension: "MK")
Currency.create(country: "Malaysia", extension: "RM")
Currency.create(country: "Maldives", extension: ".ރ")
Currency.create(country: "Mali", extension: "Fr")
Currency.create(country: "Malta", extension: "€")
Currency.create(country: "Marshall Islands", extension: "$")
Currency.create(country: "Mauritania", extension: "UM")
Currency.create(country: "Mauritius", extension: "₨")
Currency.create(country: "Mexico", extension: "$")
Currency.create(country: "Micronesia", extension: "$")
Currency.create(country: "Moldova", extension: "L")
Currency.create(country: "Monaco", extension: "€")
Currency.create(country: "Mongolia", extension: "₮")
Currency.create(country: "Montenegro", extension: "€")
Currency.create(country: "Montserrat", extension: "$")
Currency.create(country: "Morocco", extension: "د.م.")
Currency.create(country: "Mozambique", extension: "MT")
Currency.create(country: "Myanmar", extension: "Ks")
Currency.create(country: "Nagorno-Karabakh Republic", extension: "դր.")
Currency.create(country: "Namibia", extension: "$")
Currency.create(country: "Nauru", extension: "$")
Currency.create(country: "Nepal", extension: "₨")
Currency.create(country: "Netherlands[M]", extension: "€")
Currency.create(country: "New Caledonia", extension: "Fr")
Currency.create(country: "New Zealand", extension: "$")
Currency.create(country: "Nicaragua", extension: "C$")
Currency.create(country: "Niger", extension: "Fr")
Currency.create(country: "Nigeria", extension: "₦")
Currency.create(country: "Niue", extension: "$")
Currency.create(country: "Northern Cyprus", extension: "₺")
Currency.create(country: "Norway", extension: "kr")
Currency.create(country: "Oman", extension: "ر.ع.")
Currency.create(country: "Pakistan", extension: "₨")
Currency.create(country: "Palau", extension: "$")
Currency.create(country: "Palestine", extension: "₪")
Currency.create(country: "Papua New Guinea", extension: "K")
Currency.create(country: "Paraguay", extension: "₲")
Currency.create(country: "Peru", extension: "S/.")
Currency.create(country: "Philippines", extension: "₱")
Currency.create(country: "Pitcairn Islands", extension: "$")
Currency.create(country: "Poland", extension: "zł")
Currency.create(country: "Portugal", extension: "€")
Currency.create(country: "Qatar", extension: "ر.ق")
Currency.create(country: "Romania", extension: "lei")
Currency.create(country: "Russia", extension: "₽")
Currency.create(country: "Rwanda", extension: "Fr")
Currency.create(country: "Saba", extension: "$")
Currency.create(country: "Saint Helena", extension: "£")
Currency.create(country: "Saint Kitts and Nevis", extension: "$")
Currency.create(country: "Saint Lucia", extension: "$")
Currency.create(country: "Saint Vincent and the Grenadines", extension: "$")
Currency.create(country: "Samoa", extension: "T")
Currency.create(country: "San Marino", extension: "€")
Currency.create(country: "São Tomé and Príncipe", extension: "Db")
Currency.create(country: "Saudi Arabia", extension: "ر.س")
Currency.create(country: "Senegal", extension: "Fr")
Currency.create(country: "Serbia", extension: "дин.")
Currency.create(country: "Seychelles", extension: "₨")
Currency.create(country: "Sierra Leone", extension: "Le")
Currency.create(country: "Singapore", extension: "$")
Currency.create(country: "Sint Eustatius", extension: "$")
Currency.create(country: "Sint Maarten", extension: "ƒ")
Currency.create(country: "Slovakia", extension: "€")
Currency.create(country: "Slovenia", extension: "€")
Currency.create(country: "Solomon Islands", extension: "$")
Currency.create(country: "Somalia", extension: "Sh")
Currency.create(country: "Somaliland", extension: "Sl")
Currency.create(country: "South Africa", extension: "R")
Currency.create(country: "South Georgia and the South Sandwich Islands", extension: "£")
Currency.create(country: "Spain", extension: "€")
Currency.create(country: "South Sudan", extension: "£")
Currency.create(country: "Sri Lanka", extension: "Rs")
Currency.create(country: "Sudan", extension: "ج.س.")
Currency.create(country: "Suriname", extension: "$")
Currency.create(country: "Swaziland", extension: "L")
Currency.create(country: "Sweden", extension: "kr")
Currency.create(country: "Switzerland", extension: "Fr")
Currency.create(country: "Syria", extension: "£")
Currency.create(country: "Taiwan", extension: "$")
Currency.create(country: "Tajikistan", extension: "ЅМ")
Currency.create(country: "Tanzania", extension: "Sh")
Currency.create(country: "Thailand", extension: "฿")
Currency.create(country: "Togo", extension: "Fr")
Currency.create(country: "Tonga", extension: "T$")
Currency.create(country: "Transnistria", extension: "р.")
Currency.create(country: "Trinidad and Tobago", extension: "$")
Currency.create(country: "Tristan da Cunha", extension: "£")
Currency.create(country: "  Tunisia", extension: "د.ت")
Currency.create(country: "Turkey", extension: "₺")
Currency.create(country: "Turkmenistan", extension: "m")
Currency.create(country: "Turks and Caicos Islands", extension: "$")
Currency.create(country: "Tuvalu", extension: "$")
Currency.create(country: "Uganda", extension: "Sh")
Currency.create(country: "Ukraine", extension: "₴")
Currency.create(country: "United Arab Emirates", extension: "د.إ")
Currency.create(country: "United Kingdom", extension: "£")
Currency.create(country: "United States", extension: "$")
Currency.create(country: "Uruguay", extension: "$")
Currency.create(country: "Uzbekistan", extension: "₸")
Currency.create(country: "Vanuatu", extension: "Vt")
Currency.create(country: "Vatican City", extension: "€")
Currency.create(country: "Venezuela", extension: "Bs")
Currency.create(country: "Vietnam", extension: "₫")
Currency.create(country: "Wallis and Futuna", extension: "Fr")
Currency.create(country: "Zambia", extension: "ZK")

